<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\AnalyzeCodeAction_Schema.txt" />
	  <EmbeddedResource Include="Resources\UserPrompt_AnalyzeCodeAction.txt" />
	  <EmbeddedResource Include="Resources\SystemPrompt_AnalyzeCodeAction.txt" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" /> <!-- downgrade needed to run in VS 17.10 -->
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.6" />
		<!--just here support custom version of WPF-UI.Markdown-->
		<PackageReference Include="ColorCode.Core" Version="2.0.15" />
		<PackageReference Include="Markdig" Version="0.40.0" />
		<PackageReference Include="WPF-UI" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Wpf.Ui.Markdown">
			<HintPath>..\Wpf.Ui.Markdown.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Icons\add2.png" />
	  <Resource Include="Icons\delete2.png" />
	  <Resource Include="Icons\gear.png" />
	  <Resource Include="Icons\magicwand.png" />
	  <Resource Include="Icons\messages.png" />
	  <Resource Include="Icons\message_add.png" />
	  <Resource Include="__..___001_small.png" />
	</ItemGroup>
</Project>
